runtime: php55 
api_version: 1 
 
env_variables:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "peterstefanyuna"
  MYSQL_DSN: mysql:dbname=travel;unix_socket=/cloudsql/uplifted-scout-261201:us-central1:testsql

beta_settings:
  cloud_sql_instances: "uplifted-scout-261201:us-central1:testsql"

handlers: 
# Serve images as static resources 
- url: /(.+\.(gif|png|jpg))$   
  static_files: \1
  upload: .+\.(gif|png|jpg)$ 
 
 
# Serve images as static resources 
- url: /(.+\.(htm|html))$   
  static_files: \1
  upload: .+\.(htm|html)$ 
 
 
# Serve php scripts 
- url: /(.+\.php)$ 
  script: \1 

- url: /css
  static_dir: css

# - url: /javascript
#   static_dir: javascript

- url: /(.+\.js)$ 
  script: \1 

- url: /.*   
  script: index.php